name: nfc
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  intl: 0.17.0
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3

  flutter_nfc_hce:
    git:
      url: https://github.com/aleemElmozogi/flutter_nfc_hce.git
      ref: feature/REL-2876_NDEF-file-size-etc


dependency_overrides:
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
